name: 'that-changed'
description: 'A GitHub action that generates a changelog in the PDF file format.'
author: 'rdmchr'
inputs:
  token:
    description: 'GitHub personal access token. Defaults to github.token'
    required: false
    default: ${{ github.token }}
  language:
    description: 'Language of the changelog (en or de). Defaults to en'
    required: false
    default: 'en'
  upload:
    description: 'Whether to upload the changelog as a build artifact. Defaults to true'
    required: false
    default: true
  repo:
    description: 'Repository to generate the changelog for. Defaults to the current repository (<username>/<repo>)'
    required: false
    default: ${{ github.repository }}
  send_email:
    description: 'Whether to send the changelog as an email. Defaults to false'
    required: false
    default: false
  smtp_host:
    description: 'SMTP host to send the email from.'
    required: false
  smtp_port:
    description: 'SMTP port to send the email from.'
    required: false
  smtp_username:
    description: 'SMTP username to send emails.'
    required: false
  smtp_password:
    description: 'SMTP password for the SMTP user.'
    required: false
  smtp_from:
    description: 'Email address to send the email from.'
    required: false
  smtp_secure:
    description: 'Whether to use a secure connection to send the email. Defaults to false'
    required: false
    default: false
  email_to:
    description: 'Email address to send the email to. (Semicolon separated list)'
    required: false
  issue_tracker_url:
    description: 'The URL template of your issue tracker.'
    required: false
    default: ''
env:
  'GITHUB_TOKEN': 'Provided by GitHub actions'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: "orange"
  icon: "clipboard"
